import fs from "node:fs";

const dataPath = "data/programs.json";
const programs = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const checked = "2026-07-09";
const commonDocs = ["申请表", "成绩单", "毕业/预计毕业证明", "研究计划或志望理由", "语言成绩或研究科指定材料"];

function admissionInfo({
  sourceLabel,
  guideUrl,
  applicationPeriod,
  examMethod,
  supervisorContact,
  languageNotes,
  eligibilityNotes,
  requiredDocuments = commonDocs,
  verificationStatus = "待逐项核验"
}) {
  return {
    sourceLabel,
    guideUrl,
    applicationPeriod,
    examMethod,
    requiredDocuments,
    supervisorContact,
    languageNotes,
    eligibilityNotes,
    lastChecked: checked,
    verificationStatus
  };
}

const sources = {
  utokyoGeneral: admissionInfo({
    sourceLabel: "UTokyo Graduate Admissions",
    guideUrl: "https://www.u-tokyo.ac.jp/en/prospective-students/graduate_admissions.html",
    applicationPeriod: "以东京大学各研究科最新 Graduate Admissions / Application Guidelines 为准",
    examMethod: "不同研究科、专攻和英文项目选拔方式不同，通常需要材料审查、笔试、口试或面试",
    supervisorContact: "建议先确认目标研究室和教授；是否必须事前联系需按研究科募集要项判断",
    languageNotes: "英语项目、日语项目和普通入试要求差异较大，需逐项核对 TOEFL/IELTS/JLPT 要求",
    eligibilityNotes: "硕士、博士、研究生和特别项目的资格条件不同，需按目标研究科确认"
  }),
  kyotoGeneral: admissionInfo({
    sourceLabel: "Kyoto University Admissions for Graduates",
    guideUrl: "https://www.kyoto-u.ac.jp/en/education-campus/education-and-admissions/graduate-degree-programs",
    applicationPeriod: "以京都大学各研究科最新 Admissions / Application Guidelines 为准",
    examMethod: "普通入试、国际项目和研究生路径不同，需按研究科确认材料审查、考试、口试或面试",
    supervisorContact: "京都大学研究室导向较强，建议提前确认导师方向和研究计划匹配度",
    languageNotes: "日语授课项目通常要求较强日语，英文项目需核对英语成绩和项目要求",
    eligibilityNotes: "需按修士、博士后期、研究生或专业学位项目确认资格和出愿期间"
  }),
  osakaGeneral: admissionInfo({
    sourceLabel: "University of Osaka Admissions",
    guideUrl: "https://www.osaka-u.ac.jp/en/admissions",
    applicationPeriod: "以大阪大学各研究科最新 Admissions / Application Guidelines 为准",
    examMethod: "不同研究科按材料审查、笔试、口试、面试或英文项目选拔进行",
    supervisorContact: "建议结合研究室列表确认教授方向；研究生或实验室导向项目尤其需要提前确认",
    languageNotes: "英语项目和日语项目并存，语言成绩和面试语言需按项目核对",
    eligibilityNotes: "需确认目标学位、申请类别、出愿资格审查和材料邮寄/线上提交要求"
  }),
  tohokuGeneral: admissionInfo({
    sourceLabel: "Tohoku University Admissions",
    guideUrl: "https://www.tohoku.ac.jp/en/admissions/",
    applicationPeriod: "以东北大学各研究科最新 Admission Guidelines 和国际学生入学信息为准",
    examMethod: "研究科和专攻不同，通常结合材料审查、专业考试、口试或面试",
    supervisorContact: "东北大学科研导向强，建议先确认研究室、导师和可接收学生类别",
    languageNotes: "英文项目较多，但普通入试和研究室沟通仍可能要求日语能力",
    eligibilityNotes: "需按硕士、博士、研究生或国际项目确认学历、资格审查和出愿时间"
  }),
  nagoyaGeneral: admissionInfo({
    sourceLabel: "Nagoya University Graduate Admissions",
    guideUrl: "https://en.nagoya-u.ac.jp/admissions/graduate/",
    applicationPeriod: "以名古屋大学 Graduate Admissions 和各研究科最新募集要项为准",
    examMethod: "普通入试、G30 英文项目和研究生路径不同，通常结合材料审查、考试或面试",
    supervisorContact: "建议先查目标研究科研究室并确认教授方向，部分项目需要事前联系",
    languageNotes: "英文项目与日语项目语言要求不同，TOEFL/IELTS/JLPT 要逐项确认",
    eligibilityNotes: "需核对目标学位、出愿资格、预审和申请时间"
  }),
  kyushuGeneral: admissionInfo({
    sourceLabel: "Kyushu University Admissions",
    guideUrl: "https://www.kyushu-u.ac.jp/en/admission/",
    applicationPeriod: "以九州大学各学府/研究院最新 Admissions 和 Application Guidelines 为准",
    examMethod: "不同学府按材料审查、考试、口试、面试或国际项目选拔进行",
    supervisorContact: "建议先确认研究室、导师和课程方向，尤其是实验和工程类项目",
    languageNotes: "英文项目较多，但普通项目、研究生和导师沟通语言需逐项确认",
    eligibilityNotes: "硕士、博士、研究生和国际课程资格不同，需核对出愿条件"
  }),
  hokkaidoGeneral: admissionInfo({
    sourceLabel: "Hokkaido University Graduate Admissions",
    guideUrl: "https://www.global.hokudai.ac.jp/admissions/graduate-admissions/",
    applicationPeriod: "以北海道大学 Graduate Admissions 和各学院最新募集要项为准",
    examMethod: "不同学院可能包含材料审查、考试、面试或导师确认流程",
    supervisorContact: "建议提前确认目标导师和研究室，北海道大学多学院具有明确研究室导向",
    languageNotes: "英语项目、日语项目和研究生路径要求不同，需核对语言成绩和面试语言",
    eligibilityNotes: "需按硕士、博士、研究生或国际项目确认申请资格和出愿时间"
  }),
  wasedaScience: admissionInfo({
    sourceLabel: "Waseda Faculty of Science and Engineering Graduate Admissions",
    guideUrl: "https://www.waseda.jp/fsci/en/admissions_gs/",
    applicationPeriod: "官网发布 2026 年 9 月与 2027 年 4 月英文项目申请指南；日文项目另见 Japanese-based Program",
    examMethod: "英文 AO 入试不含笔试，主要根据提交材料综合评估；日文项目需按各研究科指南确认",
    supervisorContact: "官网强烈建议申请者在提交前联系潜在指导教授，并确认研究指导和导师列表",
    languageNotes: "英文项目需按指南提交语言成绩；日文项目和个别研究指导可能需要日语能力",
    eligibilityNotes: "需按基干理工、创造理工、先进理工及硕士/博士/研究生类别确认资格",
    verificationStatus: "官方页面已核验"
  }),
  wasedaGeneral: admissionInfo({
    sourceLabel: "Waseda University Admissions",
    guideUrl: "https://www.waseda.jp/top/en/admissions/",
    applicationPeriod: "以早稻田大学各研究科最新 Admissions / Application Guidelines 为准",
    examMethod: "各研究科入试类别不同，通常结合材料审查、研究计划、笔试、口试或面试",
    supervisorContact: "建议先确认研究领域和指导教员，社科与商科方向尤其需要清晰研究问题",
    languageNotes: "英文项目、日文项目和一般入试语言要求差异较大，需逐项确认",
    eligibilityNotes: "需按硕士、博士、专业职学位或研究生类别确认资格和时间"
  }),
  keioGeneral: admissionInfo({
    sourceLabel: "Keio University Graduate Admissions",
    guideUrl: "https://www.keio.ac.jp/en/admissions/grad/",
    applicationPeriod: "以庆应义塾大学 Graduate Admissions Guide 和各研究科 Application Guidebook 为准",
    examMethod: "各研究科通常按材料审查、专业考试、口试或面试进行，SFC/KMD/SDM 等项目方式不同",
    supervisorContact: "建议先确认研究科、项目和潜在指导教授；跨学科项目需突出项目匹配度",
    languageNotes: "英语/日语要求依研究科和项目不同，需按最新申请指南确认",
    eligibilityNotes: "需按硕士、博士、专业学位或 AO/一般入试确认申请资格"
  }),
  keioSdm: admissionInfo({
    sourceLabel: "Keio Graduate School of System Design and Management Admissions",
    guideUrl: "https://www.sdm.keio.ac.jp/en/admission/",
    applicationPeriod: "以 SDM Admissions 页面和最新 Application Guide 为准",
    examMethod: "SDM 注重系统设计、项目经验和跨学科能力，通常结合材料、研究/项目计划和面试评估",
    supervisorContact: "建议提前梳理研究主题、项目经历和目标教员/实验室的匹配关系",
    languageNotes: "英语和日语要求需按 SDM 当年申请指南确认",
    eligibilityNotes: "硕士、博士和社会人申请路径要求不同，需逐项核对",
    verificationStatus: "官方页面已核验"
  }),
  scienceTokyo: admissionInfo({
    sourceLabel: "Institute of Science Tokyo Admissions",
    guideUrl: "https://admissions.isct.ac.jp/en/",
    applicationPeriod: "以 Institute of Science Tokyo 最新 Graduate Admissions 和各学院 Application Guide 为准",
    examMethod: "理工、信息、生命、环境和医工方向需按学院/系确认材料审查、考试、口试或面试",
    supervisorContact: "建议先确认学院、系、实验室和导师可接收方向，研究计划需具体到方法和课题",
    languageNotes: "英文项目、国际项目和普通项目要求不同，TOEFL/IELTS/JLPT 需逐项核对",
    eligibilityNotes: "需按硕士、博士、研究生或国际研究生项目确认资格",
    verificationStatus: "待逐项核验"
  })
};

const newPrograms = [
  {
    universityName: "University of Tokyo",
    graduateSchool: "Graduate School of Frontier Sciences",
    programName: "Sustainability Science / Complex Systems",
    region: "其他",
    rankTier: 1,
    fieldCategory: "环境",
    researchFields: ["可持续发展", "复杂系统", "环境政策"],
    keywords: ["环境", "可持续", "复杂系统", "政策", "城市", "气候", "数据"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 90+ / IELTS 6.5+，具体以研究科募集要项为准",
    japaneseRequirement: "英文项目较多；日语项目建议 JLPT N2+",
    difficulty: 92,
    notes: "适合环境、城市、政策、数据分析和跨学科可持续方向申请者。",
    admissionInfo: sources.utokyoGeneral
  },
  {
    universityName: "University of Tokyo",
    graduateSchool: "Graduate School of Public Policy",
    programName: "Public Policy / International Governance",
    region: "东京",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["公共政策", "国际治理", "政策分析"],
    keywords: ["政策", "公共", "国际关系", "治理", "经济", "数据分析", "社会"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 90+ / IELTS 6.5+，英文项目需按募集要项确认",
    japaneseRequirement: "日语项目建议 JLPT N1；英文项目日语可作为加分项",
    difficulty: 91,
    notes: "适合公共政策、国际关系、经济政策和量化政策分析方向。",
    admissionInfo: sources.utokyoGeneral
  },
  {
    universityName: "University of Tokyo",
    graduateSchool: "Graduate School of Science",
    programName: "Physics / Chemistry / Earth and Planetary Science",
    region: "东京",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["物理学", "化学", "地球行星科学"],
    keywords: ["物理", "化学", "地球", "材料", "能源", "数学", "实验"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 90+ / IELTS 6.5+，具体看专攻要求",
    japaneseRequirement: "普通入试建议较强日语；研究室沟通可结合英语",
    difficulty: 95,
    notes: "适合理学基础强、科研经历明确的申请者。",
    admissionInfo: sources.utokyoGeneral
  },
  {
    universityName: "University of Tokyo",
    graduateSchool: "Graduate School of Agricultural and Life Sciences",
    programName: "Agricultural Science / Life Science / Food Systems",
    region: "东京",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["农业科学", "生命科学", "食品系统"],
    keywords: ["农业", "生命", "食品", "生物", "生态", "资源", "环境"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "日语项目建议 JLPT N2+，实验室沟通要求需确认",
    difficulty: 91,
    notes: "适合农业、生命科学、食品科学和生态资源方向。",
    admissionInfo: sources.utokyoGeneral
  },
  {
    universityName: "University of Tokyo",
    graduateSchool: "Graduate School of Arts and Sciences",
    programName: "Interdisciplinary Sciences / Area Studies",
    region: "东京",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["跨学科研究", "区域研究", "科学技术社会"],
    keywords: ["跨学科", "社会", "文化", "区域", "政策", "数据", "科技"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "多数方向建议 JLPT N1 或较强学术日语",
    difficulty: 90,
    notes: "适合跨学科、人文社科、科技社会和区域研究背景。",
    admissionInfo: sources.utokyoGeneral
  },
  {
    universityName: "Kyoto University",
    graduateSchool: "Graduate School of Science",
    programName: "Mathematics / Physics / Chemistry",
    region: "关西",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["数学", "物理学", "化学"],
    keywords: ["数学", "物理", "化学", "材料", "计算", "理论", "实验"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "普通入试建议较强日语；研究室沟通可结合英语",
    difficulty: 92,
    notes: "适合基础理学强、科研方向明确的申请者。",
    admissionInfo: sources.kyotoGeneral
  },
  {
    universityName: "Kyoto University",
    graduateSchool: "Graduate School of Agriculture",
    programName: "Applied Biosciences / Food and Environmental Sciences",
    region: "关西",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["应用生命科学", "食品科学", "环境农业"],
    keywords: ["生命", "农业", "食品", "生物", "环境", "资源", "生态"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N2+",
    difficulty: 88,
    notes: "适合农业、生命、食品和环境资源方向背景。",
    admissionInfo: sources.kyotoGeneral
  },
  {
    universityName: "Kyoto University",
    graduateSchool: "Graduate School of Economics",
    programName: "Economics / Management / Economic Policy",
    region: "关西",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["经济学", "经营学", "经济政策"],
    keywords: ["经济", "经营", "金融", "管理", "政策", "计量", "数据分析"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 90,
    notes: "适合经济、管理、计量和政策分析方向。",
    admissionInfo: sources.kyotoGeneral
  },
  {
    universityName: "Kyoto University",
    graduateSchool: "Graduate School of Management",
    programName: "Business Administration / Service and Hospitality Management",
    region: "关西",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["经营管理", "服务管理", "创新管理"],
    keywords: ["经营", "管理", "商业", "创新", "市场", "战略", "组织"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，MBA/专业项目以指南为准",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 88,
    notes: "适合商科、管理、服务创新和组织战略方向。",
    admissionInfo: sources.kyotoGeneral
  },
  {
    universityName: "Kyoto University",
    graduateSchool: "Graduate School of Energy Science",
    programName: "Energy Science / Sustainable Energy Systems",
    region: "关西",
    rankTier: 1,
    fieldCategory: "环境",
    researchFields: ["能源科学", "可持续能源", "环境系统"],
    keywords: ["能源", "环境", "可持续", "材料", "气候", "工程", "系统"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+，英语项目需单独确认",
    difficulty: 87,
    notes: "适合能源、环境、材料和工程交叉方向。",
    admissionInfo: sources.kyotoGeneral
  },
  {
    universityName: "Osaka University",
    graduateSchool: "Graduate School of Information Science and Technology",
    programName: "Information Science / Data Science / AI",
    region: "关西",
    rankTier: 1,
    fieldCategory: "信息",
    researchFields: ["信息科学", "数据科学", "人工智能"],
    keywords: ["信息", "计算机", "人工智能", "数据", "算法", "机器学习", "计算机视觉"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "日语项目建议 JLPT N2+",
    difficulty: 88,
    notes: "适合计算机、AI、数据科学和系统方向。",
    admissionInfo: sources.osakaGeneral
  },
  {
    universityName: "Osaka University",
    graduateSchool: "Graduate School of Frontier Biosciences",
    programName: "Life Science / Biomedical Systems",
    region: "关西",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生命科学", "生物医学", "系统生物学"],
    keywords: ["生命", "生物", "医学", "系统", "数据", "实验", "AI"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "研究室不同，建议 JLPT N2+ 或较强英语沟通能力",
    difficulty: 85,
    notes: "适合生命科学、生物信息、医学工程和实验方向。",
    admissionInfo: sources.osakaGeneral
  },
  {
    universityName: "Osaka University",
    graduateSchool: "Graduate School of Human Sciences",
    programName: "Human Sciences / Psychology / Sociology",
    region: "关西",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["人间科学", "心理学", "社会学"],
    keywords: ["心理", "社会", "教育", "人类", "统计", "数据", "政策"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "多数方向建议 JLPT N1",
    difficulty: 84,
    notes: "适合心理、社会、教育和人类行为研究方向。",
    admissionInfo: sources.osakaGeneral
  },
  {
    universityName: "Osaka University",
    graduateSchool: "Graduate School of Science",
    programName: "Mathematics / Physics / Chemistry",
    region: "关西",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["数学", "物理学", "化学"],
    keywords: ["数学", "物理", "化学", "材料", "理论", "实验", "计算"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "普通入试建议 JLPT N2+",
    difficulty: 86,
    notes: "适合基础理学和科研导向申请者。",
    admissionInfo: sources.osakaGeneral
  },
  {
    universityName: "Osaka University",
    graduateSchool: "Osaka School of International Public Policy",
    programName: "International Public Policy / Global Governance",
    region: "关西",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["国际公共政策", "全球治理", "经济政策"],
    keywords: ["公共", "政策", "国际关系", "治理", "经济", "法律", "社会"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "英文项目可重点看英语；日语项目建议 JLPT N1",
    difficulty: 84,
    notes: "适合政策、国际关系、经济政策和全球治理方向。",
    admissionInfo: sources.osakaGeneral
  },
  {
    universityName: "Tohoku University",
    graduateSchool: "Graduate School of Environmental Studies",
    programName: "Environmental Studies / Sustainable Systems",
    region: "其他",
    rankTier: 1,
    fieldCategory: "环境",
    researchFields: ["环境科学", "可持续系统", "资源循环"],
    keywords: ["环境", "可持续", "资源", "能源", "气候", "循环", "政策"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+，英语项目需单独确认",
    difficulty: 82,
    notes: "适合环境、资源循环、能源和可持续方向。",
    admissionInfo: sources.tohokuGeneral
  },
  {
    universityName: "Tohoku University",
    graduateSchool: "Graduate School of Life Sciences",
    programName: "Molecular Life Sciences / Ecology",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生命科学", "分子生物学", "生态学"],
    keywords: ["生命", "生物", "生态", "分子", "农业", "环境", "实验"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "研究室不同，建议具备日语或英语科研沟通能力",
    difficulty: 83,
    notes: "适合生命科学、生物、生态和实验科研方向。",
    admissionInfo: sources.tohokuGeneral
  },
  {
    universityName: "Tohoku University",
    graduateSchool: "Graduate School of Economics and Management",
    programName: "Economics / Management / Accounting",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["经济学", "经营学", "会计学"],
    keywords: ["经济", "经营", "管理", "会计", "金融", "计量", "数据分析"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 82,
    notes: "适合经济、管理、会计和数据分析方向。",
    admissionInfo: sources.tohokuGeneral
  },
  {
    universityName: "Tohoku University",
    graduateSchool: "Graduate School of Agricultural Science",
    programName: "Agricultural Science / Food and Resource Biology",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["农业科学", "食品资源", "应用生命科学"],
    keywords: ["农业", "食品", "生命", "资源", "生态", "生物", "环境"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+",
    difficulty: 80,
    notes: "适合农业、食品、生物资源和环境方向。",
    admissionInfo: sources.tohokuGeneral
  },
  {
    universityName: "Tohoku University",
    graduateSchool: "Graduate School of Science",
    programName: "Mathematics / Physics / Earth Science",
    region: "其他",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["数学", "物理学", "地球科学"],
    keywords: ["数学", "物理", "地球", "化学", "材料", "计算", "理论"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "普通入试建议 JLPT N2+",
    difficulty: 84,
    notes: "适合基础理学、地球科学和材料相关科研方向。",
    admissionInfo: sources.tohokuGeneral
  },
  {
    universityName: "Nagoya University",
    graduateSchool: "Graduate School of Science",
    programName: "Mathematics / Physics / Chemistry",
    region: "其他",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["数学", "物理学", "化学"],
    keywords: ["数学", "物理", "化学", "材料", "理论", "实验", "计算"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "普通入试建议 JLPT N2+",
    difficulty: 83,
    notes: "适合基础理学、材料和计算科学方向。",
    admissionInfo: sources.nagoyaGeneral
  },
  {
    universityName: "Nagoya University",
    graduateSchool: "Graduate School of Bioagricultural Sciences",
    programName: "Bioagricultural Science / Applied Bioscience",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生物农业科学", "应用生命科学", "食品与资源"],
    keywords: ["农业", "生物", "生命", "食品", "资源", "生态", "环境"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+",
    difficulty: 80,
    notes: "适合农业、生物、食品和资源环境方向。",
    admissionInfo: sources.nagoyaGeneral
  },
  {
    universityName: "Nagoya University",
    graduateSchool: "Graduate School of Economics",
    programName: "Economics / Management Systems",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["经济学", "经营学", "管理系统"],
    keywords: ["经济", "经营", "管理", "金融", "计量", "数据分析", "组织"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 81,
    notes: "适合经济、经营、计量和管理系统方向。",
    admissionInfo: sources.nagoyaGeneral
  },
  {
    universityName: "Nagoya University",
    graduateSchool: "Graduate School of International Development",
    programName: "International Development / Governance",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["国际开发", "发展政策", "全球治理"],
    keywords: ["国际", "开发", "政策", "治理", "经济", "社会", "教育"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "英文项目较多；日语能力可作为加分项",
    difficulty: 80,
    notes: "适合国际发展、公共政策、教育发展和全球治理方向。",
    admissionInfo: sources.nagoyaGeneral
  },
  {
    universityName: "Nagoya University",
    graduateSchool: "Graduate School of Medicine",
    programName: "Medical Science / Public Health",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["医学科学", "公共卫生", "生命医科学"],
    keywords: ["医学", "公共卫生", "生命", "生物", "数据", "健康", "统计"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "医学相关项目需按研究科确认日语和资格条件",
    difficulty: 84,
    notes: "适合生命医科学、公共卫生、生物统计和健康数据方向。",
    admissionInfo: sources.nagoyaGeneral
  },
  {
    universityName: "Kyushu University",
    graduateSchool: "Graduate School of Engineering",
    programName: "Civil Engineering / Architecture / Urban Infrastructure",
    region: "其他",
    rankTier: 1,
    fieldCategory: "工学",
    researchFields: ["土木工程", "建筑工程", "城市基础设施"],
    keywords: ["土木", "建筑", "结构", "抗震", "都市", "基础设施", "环境"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+，英文项目需单独确认",
    difficulty: 81,
    notes: "适合建筑、土木、结构、防灾和基础设施方向。",
    admissionInfo: sources.kyushuGeneral
  },
  {
    universityName: "Kyushu University",
    graduateSchool: "Graduate School of Human-Environment Studies",
    programName: "Architecture / Urban Design / Human Environment",
    region: "其他",
    rankTier: 1,
    fieldCategory: "设计",
    researchFields: ["建筑设计", "城市设计", "人居环境"],
    keywords: ["建筑", "城市", "设计", "环境", "规划", "用户体验", "人因"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N2+，作品集或研究计划很重要",
    difficulty: 80,
    notes: "适合建筑、城市、人居环境和设计研究方向。",
    admissionInfo: sources.kyushuGeneral
  },
  {
    universityName: "Kyushu University",
    graduateSchool: "Graduate School of Bioresource and Bioenvironmental Sciences",
    programName: "Bioresource / Bioenvironment / Food Science",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生物资源", "生物环境", "食品科学"],
    keywords: ["生物", "农业", "食品", "资源", "环境", "生态", "生命"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+",
    difficulty: 79,
    notes: "适合农业、生物资源、食品和环境生命方向。",
    admissionInfo: sources.kyushuGeneral
  },
  {
    universityName: "Kyushu University",
    graduateSchool: "Graduate School of Economics",
    programName: "Economics / Business Administration",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["经济学", "经营学", "产业经济"],
    keywords: ["经济", "经营", "商业", "金融", "产业", "管理", "计量"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 79,
    notes: "适合经济、经营、产业分析和计量方向。",
    admissionInfo: sources.kyushuGeneral
  },
  {
    universityName: "Kyushu University",
    graduateSchool: "Graduate School of Integrated Sciences for Global Society",
    programName: "Integrated Sciences / Area Studies / Global Society",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["综合科学", "区域研究", "全球社会"],
    keywords: ["社会", "国际", "区域", "文化", "政策", "环境", "数据"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "根据研究方向建议 JLPT N1/N2",
    difficulty: 78,
    notes: "适合区域研究、全球社会、环境社会和跨学科方向。",
    admissionInfo: sources.kyushuGeneral
  },
  {
    universityName: "Hokkaido University",
    graduateSchool: "Graduate School of Information Science and Technology",
    programName: "Computer Science / AI / Information Systems",
    region: "其他",
    rankTier: 1,
    fieldCategory: "信息",
    researchFields: ["计算机科学", "人工智能", "信息系统"],
    keywords: ["计算机", "人工智能", "数据", "系统", "算法", "机器学习", "图像处理"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N2+，英文研究需确认导师沟通语言",
    difficulty: 80,
    notes: "适合计算机、AI、数据和信息系统方向。",
    admissionInfo: sources.hokkaidoGeneral
  },
  {
    universityName: "Hokkaido University",
    graduateSchool: "Graduate School of Life Science",
    programName: "Life Science / Biomedical Science",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生命科学", "生物医学", "分子生物学"],
    keywords: ["生命", "生物", "医学", "分子", "数据", "实验", "健康"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "研究室不同，建议 JLPT N2+ 或英语科研沟通能力",
    difficulty: 79,
    notes: "适合生命科学、生物医学和分子生物学方向。",
    admissionInfo: sources.hokkaidoGeneral
  },
  {
    universityName: "Hokkaido University",
    graduateSchool: "Graduate School of Chemical Sciences and Engineering",
    programName: "Chemical Science / Materials Chemistry",
    region: "其他",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["化学", "材料化学", "化学工程"],
    keywords: ["化学", "材料", "能源", "环境", "实验", "工程", "纳米"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+，英文项目需确认",
    difficulty: 79,
    notes: "适合化学、材料、能源和化工方向。",
    admissionInfo: sources.hokkaidoGeneral
  },
  {
    universityName: "Hokkaido University",
    graduateSchool: "Graduate School of Global Food Resources",
    programName: "Global Food Resources / Food Security",
    region: "其他",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["全球食物资源", "食品安全", "农业资源"],
    keywords: ["食品", "农业", "资源", "环境", "可持续", "政策", "生命"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+",
    japaneseRequirement: "英文项目较多；日语能力可作为加分项",
    difficulty: 77,
    notes: "适合食品安全、农业资源和可持续发展方向。",
    admissionInfo: sources.hokkaidoGeneral
  },
  {
    universityName: "Hokkaido University",
    graduateSchool: "Public Policy School",
    programName: "Public Policy / Regional Governance",
    region: "其他",
    rankTier: 1,
    fieldCategory: "商科社科",
    researchFields: ["公共政策", "区域治理", "社会政策"],
    keywords: ["政策", "公共", "治理", "区域", "社会", "经济", "法律"],
    degreeOptions: ["硕士"],
    englishRequirement: "建议 TOEFL 79+ / IELTS 6.0+，具体以专业学位项目为准",
    japaneseRequirement: "日语项目通常建议 JLPT N1",
    difficulty: 77,
    notes: "适合公共政策、区域治理和社会政策方向。",
    admissionInfo: sources.hokkaidoGeneral
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Fundamental Science and Engineering",
    programName: "Computer Science / Communications Engineering",
    region: "东京",
    rankTier: 2,
    fieldCategory: "信息",
    researchFields: ["计算机科学", "通信工程", "人工智能"],
    keywords: ["计算机", "通信", "人工智能", "数据", "算法", "系统", "图像处理"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "英文 AO 项目需按指南提交英语成绩，建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日文项目建议 JLPT N2+；英文项目日语不是硬性前提",
    difficulty: 82,
    notes: "补足早稻田理工信息方向，适合 CS、通信、AI 和系统方向。",
    admissionInfo: sources.wasedaScience
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Creative Science and Engineering",
    programName: "Architecture / Civil and Environmental Engineering",
    region: "东京",
    rankTier: 2,
    fieldCategory: "工学",
    researchFields: ["建筑", "土木工程", "环境工程"],
    keywords: ["建筑", "土木", "结构", "抗震", "环境", "城市", "基础设施"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "英文 AO 项目建议 TOEFL 80+ / IELTS 6.0+；日文项目以指南为准",
    japaneseRequirement: "日文项目建议 JLPT N2+，建筑/土木研究计划表达很重要",
    difficulty: 81,
    notes: "适合抗震结构、建筑、土木、城市基础设施和环境工程方向。",
    admissionInfo: sources.wasedaScience
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Advanced Science and Engineering",
    programName: "Life Science / Materials / Applied Chemistry",
    region: "东京",
    rankTier: 2,
    fieldCategory: "生命农业",
    researchFields: ["生命科学", "材料科学", "应用化学"],
    keywords: ["生命", "材料", "化学", "生物", "能源", "医学", "纳米"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "英文 AO 项目建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日文项目建议 JLPT N2+",
    difficulty: 80,
    notes: "适合材料、化学、生命科学和医工交叉方向。",
    admissionInfo: sources.wasedaScience
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Environment and Energy Engineering",
    programName: "Environment and Energy Engineering",
    region: "东京",
    rankTier: 2,
    fieldCategory: "环境",
    researchFields: ["环境工程", "能源系统", "可持续工程"],
    keywords: ["环境", "能源", "可持续", "工程", "气候", "材料", "系统"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，具体以研究科指南为准",
    japaneseRequirement: "建议 JLPT N2+ 或较强英语沟通能力",
    difficulty: 78,
    notes: "适合环境能源、低碳技术和可持续工程方向。",
    admissionInfo: sources.wasedaScience
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Human Sciences",
    programName: "Human Sciences / UX / Cognitive Science",
    region: "东京",
    rankTier: 2,
    fieldCategory: "设计",
    researchFields: ["人间科学", "用户体验", "认知科学"],
    keywords: ["用户体验", "认知", "心理", "设计", "人因", "数据", "社会"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1/N2",
    difficulty: 77,
    notes: "适合 UX、人因、认知、心理和用户研究方向。",
    admissionInfo: sources.wasedaGeneral
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Asia-Pacific Studies",
    programName: "International Relations / Area Studies",
    region: "东京",
    rankTier: 2,
    fieldCategory: "商科社科",
    researchFields: ["国际关系", "区域研究", "国际合作"],
    keywords: ["国际关系", "区域", "政策", "合作", "社会", "政治", "发展"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "英文项目建议 TOEFL 80+ / IELTS 6.5+",
    japaneseRequirement: "英文项目日语可作为加分项；日文研究需较强日语",
    difficulty: 77,
    notes: "适合国际关系、亚太研究和国际合作方向。",
    admissionInfo: sources.wasedaGeneral
  },
  {
    universityName: "Waseda University",
    graduateSchool: "Graduate School of Social Sciences",
    programName: "Social Sciences / Policy Studies",
    region: "东京",
    rankTier: 2,
    fieldCategory: "商科社科",
    researchFields: ["社会科学", "政策研究", "社会创新"],
    keywords: ["社会", "政策", "公共", "创新", "经济", "法律", "数据"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 76,
    notes: "适合社会科学、政策、法律经济交叉和社会创新方向。",
    admissionInfo: sources.wasedaGeneral
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of Science and Technology",
    programName: "Computer Science / Open Systems Management",
    region: "东京",
    rankTier: 2,
    fieldCategory: "信息",
    researchFields: ["计算机科学", "开放系统", "人工智能"],
    keywords: ["计算机", "系统", "人工智能", "数据", "算法", "机器学习", "图像处理"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，具体以理工学研究科指南为准",
    japaneseRequirement: "建议 JLPT N2+，研究室沟通语言需确认",
    difficulty: 81,
    notes: "补足庆应理工信息方向，适合 CS、AI、系统和数据方向。",
    admissionInfo: sources.keioGeneral
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of Science and Technology",
    programName: "Electronics / Electrical Engineering / Applied Physics",
    region: "东京",
    rankTier: 2,
    fieldCategory: "工学",
    researchFields: ["电子电气", "应用物理", "光电工程"],
    keywords: ["电子", "电气", "物理", "材料", "通信", "能源", "半导体"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+，具体看研究室",
    difficulty: 80,
    notes: "适合电子、电气、应用物理、半导体和光电方向。",
    admissionInfo: sources.keioGeneral
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of Policy and Media",
    programName: "Policy and Media / Data and Society",
    region: "东京",
    rankTier: 2,
    fieldCategory: "商科社科",
    researchFields: ["政策媒体", "数据社会", "创新政策"],
    keywords: ["政策", "媒体", "数据", "社会", "创新", "用户体验", "治理"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，英文项目以指南为准",
    japaneseRequirement: "日英双语环境，具体语言要求需按项目确认",
    difficulty: 79,
    notes: "适合 SFC 风格的政策、媒体、数据社会和创新研究。",
    admissionInfo: sources.keioGeneral
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of System Design and Management",
    programName: "System Design / Project Management",
    region: "东京",
    rankTier: 2,
    fieldCategory: "工学",
    researchFields: ["系统设计", "项目管理", "服务系统"],
    keywords: ["系统", "设计", "管理", "项目", "创新", "产品", "工程"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，具体以 SDM 指南为准",
    japaneseRequirement: "日英项目并存，需按申请类别确认",
    difficulty: 78,
    notes: "适合系统工程、项目管理、服务设计和产品创新方向。",
    admissionInfo: sources.keioSdm
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of Economics",
    programName: "Economics / Econometrics / Economic Policy",
    region: "东京",
    rankTier: 2,
    fieldCategory: "商科社科",
    researchFields: ["经济学", "计量经济", "经济政策"],
    keywords: ["经济", "计量", "金融", "政策", "数据分析", "统计", "管理"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 79,
    notes: "适合经济、计量、金融和政策分析方向。",
    admissionInfo: sources.keioGeneral
  },
  {
    universityName: "Keio University",
    graduateSchool: "Graduate School of Human Relations",
    programName: "Psychology / Sociology / Education",
    region: "东京",
    rankTier: 2,
    fieldCategory: "商科社科",
    researchFields: ["心理学", "社会学", "教育学"],
    keywords: ["心理", "社会", "教育", "统计", "数据", "人类", "行为"],
    degreeOptions: ["硕士", "博士"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N1",
    difficulty: 77,
    notes: "适合心理、社会、教育、人类行为和统计研究方向。",
    admissionInfo: sources.keioGeneral
  },
  {
    universityName: "Institute of Science Tokyo",
    graduateSchool: "School of Engineering",
    programName: "Civil and Environmental Engineering / Architecture",
    region: "东京",
    rankTier: 1,
    fieldCategory: "工学",
    researchFields: ["土木环境工学", "建筑", "都市基础设施"],
    keywords: ["土木", "建筑", "结构", "抗震", "环境", "基础设施", "城市"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+，具体以学院指南为准",
    japaneseRequirement: "日语项目建议 JLPT N2+，英文项目需单独确认",
    difficulty: 88,
    notes: "补回原始需求中的东京科学大学，适合工学、结构、建筑和环境方向。",
    admissionInfo: sources.scienceTokyo
  },
  {
    universityName: "Institute of Science Tokyo",
    graduateSchool: "School of Computing",
    programName: "Computer Science / Artificial Intelligence",
    region: "东京",
    rankTier: 1,
    fieldCategory: "信息",
    researchFields: ["计算机科学", "人工智能", "数据科学"],
    keywords: ["计算机", "人工智能", "数据", "算法", "机器学习", "计算机视觉", "图像处理"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 85+ / IELTS 6.5+",
    japaneseRequirement: "英文项目较多；普通项目需确认日语要求",
    difficulty: 90,
    notes: "适合 CS、AI、计算机视觉、数据和系统方向。",
    admissionInfo: sources.scienceTokyo
  },
  {
    universityName: "Institute of Science Tokyo",
    graduateSchool: "School of Materials and Chemical Technology",
    programName: "Materials Science / Chemical Science",
    region: "东京",
    rankTier: 1,
    fieldCategory: "理学",
    researchFields: ["材料科学", "化学工程", "能源材料"],
    keywords: ["材料", "化学", "能源", "环境", "纳米", "实验", "工程"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "建议 JLPT N2+ 或英语科研沟通能力",
    difficulty: 87,
    notes: "适合材料、化学、能源和纳米方向。",
    admissionInfo: sources.scienceTokyo
  },
  {
    universityName: "Institute of Science Tokyo",
    graduateSchool: "School of Life Science and Technology",
    programName: "Life Science / Bioengineering",
    region: "东京",
    rankTier: 1,
    fieldCategory: "生命农业",
    researchFields: ["生命科学", "生物工程", "医工交叉"],
    keywords: ["生命", "生物", "医学", "工程", "数据", "实验", "健康"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "研究室不同，需确认语言要求",
    difficulty: 86,
    notes: "适合生命科学、生物工程和医工交叉方向。",
    admissionInfo: sources.scienceTokyo
  },
  {
    universityName: "Institute of Science Tokyo",
    graduateSchool: "School of Environment and Society",
    programName: "Environmental and Social Systems / Innovation Science",
    region: "东京",
    rankTier: 1,
    fieldCategory: "环境",
    researchFields: ["环境社会系统", "创新科学", "技术经营"],
    keywords: ["环境", "社会", "创新", "管理", "政策", "技术", "可持续"],
    degreeOptions: ["硕士", "博士", "研究生"],
    englishRequirement: "建议 TOEFL 80+ / IELTS 6.0+",
    japaneseRequirement: "日语项目建议 JLPT N2+，英文项目需确认",
    difficulty: 85,
    notes: "适合环境系统、技术经营、创新和可持续社会方向。",
    admissionInfo: sources.scienceTokyo
  }
];

const existingIds = new Set(programs.map((program) => `${program.universityName}|${program.graduateSchool}|${program.programName}`));
let added = 0;

for (const program of newPrograms) {
  const id = `${program.universityName}|${program.graduateSchool}|${program.programName}`;
  if (existingIds.has(id)) continue;
  programs.push(program);
  existingIds.add(id);
  added += 1;
}

fs.writeFileSync(dataPath, `${JSON.stringify(programs, null, 2)}\n`, "utf8");
console.log(`Added ${added} programs. Total: ${programs.length}.`);
